import { CampaignCard } from "@/sections/CampaignsSection/components/CampaignCard";

export const CampaignCarousel = () => {
  return (
    <div className="items-center box-border caret-transparent flex justify-between mt-2.5">
      <button className="text-gray-600 text-[10px] bg-zinc-900 caret-transparent block leading-[15px] text-center mr-1 p-2 rounded-full">
        <img
          src="https://c.animaapp.com/mh4w5bh5ddZvQu/assets/icon-13.svg"
          alt="Icon"
          className="box-border caret-transparent h-2.5 w-2.5"
        />
      </button>
      <div className="box-border caret-transparent gap-x-6 flex flex-wrap justify-center overflow-x-hidden overflow-y-auto gap-y-6 w-full">
        <CampaignCard
          imageUrl="https://c.animaapp.com/mh4w5bh5ddZvQu/assets/ozlo2.webp"
          imageAlt="fund"
          tagIconUrl="https://c.animaapp.com/mh4w5bh5ddZvQu/assets/type.9025aba9.svg"
          tagText="Fundraiser"
          title="Ozlo Sleepbuds: The Next-Generation Sleepbuds "
          description="Does your racing mind prevent you from falling asleep? Do annoying city sounds, your partner's snoring, or other sleep disturbances keep you from sleeping soundly?

Then like 1 in 3 Americans, you're suffering from trash sleep, and Ozlo Sleep is here to help. Calm your racing mind and put your brain to bed with Ozlo Sleepbuds®."
          raisedAmount="0.0"
          targetAmount="0.005"
          daysLeft="-490"
          userImageUrl="https://c.animaapp.com/mh4w5bh5ddZvQu/assets/thirdweb.8f9bb89b.png"
          creatorAddress="0x67E6436A1b0922f2aCf334e50dcB52ceAB8a54d2"
          containerVariant="bg-zinc-900 shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0.1)_0px_10px_15px_-3px,rgba(0,0,0,0.1)_0px_4px_6px_-4px] box-border caret-transparent max-w-none w-full rounded-[15px] md:max-w-60"
          imageVariant="box-border caret-transparent h-[150px] max-w-full object-cover w-full rounded-[15px]"
          contentVariant="box-border caret-transparent flex flex-col p-4"
          tagContainerVariant="items-center box-border caret-transparent flex mb-[18px]"
          tagIconVariant="box-border caret-transparent h-[17px] max-w-full object-contain w-[17px]"
          tagTextVariant="text-gray-500 text-xs font-medium box-border caret-transparent leading-[18px] ml-3 mt-0.5 font-epilogue"
          textContainerVariant="box-border caret-transparent"
          titleVariant="font-semibold box-border caret-transparent leading-[26px] text-left text-ellipsis text-nowrap overflow-hidden font-epilogue"
          descriptionVariant="text-gray-500 box-border caret-transparent leading-[18px] text-left text-ellipsis text-nowrap overflow-hidden mt-[5px] font-epilogue"
          statsContainerVariant="box-border caret-transparent gap-x-2 flex flex-wrap justify-between gap-y-2 mt-[15px]"
          statItemVariant="box-border caret-transparent flex flex-col"
          statValueVariant="text-gray-400 text-sm font-semibold box-border caret-transparent leading-[22px] font-epilogue"
          statLabelVariant="text-gray-500 text-xs box-border caret-transparent leading-[18px] mt-[3px] font-epilogue"
          creatorContainerVariant="items-center box-border caret-transparent gap-x-3 flex gap-y-3 mt-5"
          creatorImageContainerVariant="items-center bg-neutral-900 box-border caret-transparent flex h-[30px] justify-center w-[30px] rounded-full"
          creatorImageVariant="box-border caret-transparent h-3/6 max-w-full object-contain w-6/12"
          creatorTextVariant="text-gray-500 text-xs box-border caret-transparent basis-[0%] grow leading-[18px] text-ellipsis text-nowrap overflow-hidden font-epilogue"
          creatorAddressVariant="text-gray-400 box-border caret-transparent text-nowrap"
        />
        <CampaignCard
          imageUrl="https://c.animaapp.com/mh4w5bh5ddZvQu/assets/nobel2.webp"
          imageAlt="fund"
          tagIconUrl="https://c.animaapp.com/mh4w5bh5ddZvQu/assets/type.9025aba9.svg"
          tagText="Fundraiser"
          title="NOBEL 2.0 Kneeling Ergo Chair for Upright Posture "
          description={
            "With its innovative upgraded design, the NOBEL 2.0 Kneeling Chair provides optimal posture alignment, relieving pressure on your back and promoting better spinal health.\n\n✅ Pain Relief for Neck, Back & Shoulders\n✅ Active Sitting for Core Engagement\n✅ Natural Upright Posture\n\nThe Result: You’ll have a pain-free sitting experience with Nobel 2.0"
          }
          raisedAmount="0.001"
          targetAmount="0.001"
          daysLeft="-512"
          userImageUrl="https://c.animaapp.com/mh4w5bh5ddZvQu/assets/thirdweb.8f9bb89b.png"
          creatorAddress="0x67E6436A1b0922f2aCf334e50dcB52ceAB8a54d2"
          containerVariant="bg-transparent shadow-none box-content caret-black min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-zinc-900 md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0.1)_0px_10px_15px_-3px,rgba(0,0,0,0.1)_0px_4px_6px_-4px] md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[15px]"
          imageVariant="box-content caret-black h-auto max-w-none object-fill w-auto rounded-none md:aspect-auto md:box-border md:caret-transparent md:h-[150px] md:max-w-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[15px]"
          contentVariant="box-content caret-black block flex-row md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:p-4 md:scroll-m-0 md:scroll-p-[auto]"
          tagContainerVariant="[align-items:normal] box-content caret-black block min-h-0 min-w-0 mb-0 md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mb-[18px] md:scroll-m-0 md:scroll-p-[auto]"
          tagIconVariant="box-content caret-black h-auto max-w-none min-h-0 min-w-0 object-fill w-auto md:aspect-auto md:box-border md:caret-transparent md:h-[17px] md:max-w-full md:min-h-[auto] md:min-w-[auto] md:object-contain md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[17px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
          tagTextVariant="text-black text-base font-normal box-content caret-black leading-[normal] min-h-0 min-w-0 ml-0 mt-0 font-times md:text-gray-500 md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:leading-[18px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:ml-3 md:mt-0.5 md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          textContainerVariant="box-content caret-black min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
          titleVariant="font-bold box-content caret-black leading-[normal] text-start text-clip text-wrap font-times md:font-semibold md:aspect-auto md:box-border md:caret-transparent md:leading-[26px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          descriptionVariant="text-black box-content caret-black leading-[normal] text-start text-clip text-wrap mt-0 font-times md:text-gray-500 md:aspect-auto md:box-border md:caret-transparent md:leading-[18px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:mt-[5px] md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          statsContainerVariant="box-content caret-black gap-x-[normal] block flex-nowrap justify-normal min-h-0 min-w-0 gap-y-[normal] mt-0 md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:flex-wrap md:justify-between md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-[15px] md:scroll-m-0 md:scroll-p-[auto]"
          statItemVariant="box-content caret-black block flex-row min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
          statValueVariant="text-black text-base font-bold box-content caret-black leading-[normal] min-h-0 min-w-0 font-times md:text-gray-400 md:text-sm md:font-semibold md:aspect-auto md:box-border md:caret-transparent md:leading-[22px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          statLabelVariant="text-black text-base box-content caret-black leading-[normal] min-h-0 min-w-0 mt-0 font-times md:text-gray-500 md:text-xs md:aspect-auto md:box-border md:caret-transparent md:leading-[18px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-[3px] md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          creatorContainerVariant="[align-items:normal] box-content caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] mt-0 md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-5 md:scroll-m-0 md:scroll-p-[auto]"
          creatorImageContainerVariant="[align-items:normal] bg-transparent box-content caret-black block h-auto justify-normal min-h-0 min-w-0 w-auto rounded-none md:items-center md:aspect-auto md:bg-neutral-900 md:box-border md:caret-transparent md:flex md:h-[30px] md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[30px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-full"
          creatorImageVariant="box-content caret-black h-auto max-w-none min-h-0 min-w-0 object-fill w-auto md:aspect-auto md:box-border md:caret-transparent md:h-3/6 md:max-w-full md:min-h-[auto] md:min-w-[auto] md:object-contain md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6/12 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
          creatorTextVariant="text-black text-base box-content caret-black basis-auto grow-0 leading-[normal] min-h-0 min-w-0 text-clip text-wrap font-times md:text-gray-500 md:text-xs md:aspect-auto md:box-border md:caret-transparent md:basis-[0%] md:grow md:leading-[18px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          creatorAddressVariant="text-black box-content caret-black text-wrap md:text-gray-400 md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
        />
        <CampaignCard
          imageUrl="https://c.animaapp.com/mh4w5bh5ddZvQu/assets/shaver.png"
          imageAlt="fund"
          tagIconUrl="https://c.animaapp.com/mh4w5bh5ddZvQu/assets/type.9025aba9.svg"
          tagText="Fundraiser"
          title="MOTOR-ZERO 2.0:A new definition of a razor "
          description="Portable|Mini|self-sharpening Blades|Replaceable Blades|IPX7 waterproof|With Mirror|LED Display "
          raisedAmount="0.0"
          targetAmount="0.005"
          daysLeft="-498"
          userImageUrl="https://c.animaapp.com/mh4w5bh5ddZvQu/assets/thirdweb.8f9bb89b.png"
          creatorAddress="0x67E6436A1b0922f2aCf334e50dcB52ceAB8a54d2"
          containerVariant="bg-transparent shadow-none box-content caret-black max-w-none min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-zinc-900 md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0.1)_0px_10px_15px_-3px,rgba(0,0,0,0.1)_0px_4px_6px_-4px] md:box-border md:caret-transparent md:max-w-60 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[15px]"
          imageVariant="box-content caret-black h-auto max-w-none object-fill w-auto rounded-none md:aspect-auto md:box-border md:caret-transparent md:h-[150px] md:max-w-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[15px]"
          contentVariant="box-content caret-black block flex-row md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:p-4 md:scroll-m-0 md:scroll-p-[auto]"
          tagContainerVariant="[align-items:normal] box-content caret-black block min-h-0 min-w-0 mb-0 md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mb-[18px] md:scroll-m-0 md:scroll-p-[auto]"
          tagIconVariant="box-content caret-black h-auto max-w-none min-h-0 min-w-0 object-fill w-auto md:aspect-auto md:box-border md:caret-transparent md:h-[17px] md:max-w-full md:min-h-[auto] md:min-w-[auto] md:object-contain md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[17px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
          tagTextVariant="text-black text-base font-normal box-content caret-black leading-[normal] min-h-0 min-w-0 ml-0 mt-0 font-times md:text-gray-500 md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:leading-[18px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:ml-3 md:mt-0.5 md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          textContainerVariant="box-content caret-black min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
          titleVariant="font-bold box-content caret-black leading-[normal] text-start text-clip text-wrap font-times md:font-semibold md:aspect-auto md:box-border md:caret-transparent md:leading-[26px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          descriptionVariant="text-black box-content caret-black leading-[normal] text-start text-clip text-wrap mt-0 font-times md:text-gray-500 md:aspect-auto md:box-border md:caret-transparent md:leading-[18px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:mt-[5px] md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          statsContainerVariant="box-content caret-black gap-x-[normal] block flex-nowrap justify-normal min-h-0 min-w-0 gap-y-[normal] mt-0 md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:flex-wrap md:justify-between md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-[15px] md:scroll-m-0 md:scroll-p-[auto]"
          statItemVariant="box-content caret-black block flex-row min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
          statValueVariant="text-black text-base font-bold box-content caret-black leading-[normal] min-h-0 min-w-0 font-times md:text-gray-400 md:text-sm md:font-semibold md:aspect-auto md:box-border md:caret-transparent md:leading-[22px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          statLabelVariant="text-black text-base box-content caret-black leading-[normal] min-h-0 min-w-0 mt-0 font-times md:text-gray-500 md:text-xs md:aspect-auto md:box-border md:caret-transparent md:leading-[18px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-[3px] md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          creatorContainerVariant="[align-items:normal] box-content caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] mt-0 md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-5 md:scroll-m-0 md:scroll-p-[auto]"
          creatorImageContainerVariant="[align-items:normal] bg-transparent box-content caret-black block h-auto justify-normal min-h-0 min-w-0 w-auto rounded-none md:items-center md:aspect-auto md:bg-neutral-900 md:box-border md:caret-transparent md:flex md:h-[30px] md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[30px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-full"
          creatorImageVariant="box-content caret-black h-auto max-w-none min-h-0 min-w-0 object-fill w-auto md:aspect-auto md:box-border md:caret-transparent md:h-3/6 md:max-w-full md:min-h-[auto] md:min-w-[auto] md:object-contain md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6/12 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
          creatorTextVariant="text-black text-base box-content caret-black basis-auto grow-0 leading-[normal] min-h-0 min-w-0 text-clip text-wrap font-times md:text-gray-500 md:text-xs md:aspect-auto md:box-border md:caret-transparent md:basis-[0%] md:grow md:leading-[18px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          creatorAddressVariant="text-black box-content caret-black text-wrap md:text-gray-400 md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
        />
        <CampaignCard
          imageUrl="https://c.animaapp.com/mh4w5bh5ddZvQu/assets/makerpro.jpg"
          imageAlt="fund"
          tagIconUrl="https://c.animaapp.com/mh4w5bh5ddZvQu/assets/type.9025aba9.svg"
          tagText="Fundraiser"
          title="Maker Pro : 17-in-1 Multipurpose Tool Set "
          description="Professional tool set with 17 different power tools with a single drill body. save money,space,time! "
          raisedAmount="0.0"
          targetAmount="0.006"
          daysLeft="-505"
          userImageUrl="https://c.animaapp.com/mh4w5bh5ddZvQu/assets/thirdweb.8f9bb89b.png"
          creatorAddress="0x67E6436A1b0922f2aCf334e50dcB52ceAB8a54d2"
          containerVariant="bg-transparent shadow-none box-content caret-black min-w-0 min-h-0 w-auto rounded-none md:aspect-auto md:bg-zinc-900 md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0.1)_0px_10px_15px_-3px,rgba(0,0,0,0.1)_0px_4px_6px_-4px] md:box-border md:caret-transparent md:max-w-60 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[15px]"
          imageVariant="box-content caret-black h-auto max-w-none object-fill w-auto rounded-none md:aspect-auto md:box-border md:caret-transparent md:h-[150px] md:max-w-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[15px]"
          contentVariant="box-content caret-black block flex-row md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:p-4 md:scroll-m-0 md:scroll-p-[auto]"
          tagContainerVariant="[align-items:normal] box-content caret-black block min-h-0 min-w-0 mb-0 md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mb-[18px] md:scroll-m-0 md:scroll-p-[auto]"
          tagIconVariant="box-content caret-black h-auto max-w-none min-h-0 min-w-0 object-fill w-auto md:aspect-auto md:box-border md:caret-transparent md:h-[17px] md:max-w-full md:min-h-[auto] md:min-w-[auto] md:object-contain md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[17px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
          tagTextVariant="text-black text-base font-normal box-content caret-black leading-[normal] min-h-0 min-w-0 ml-0 mt-0 font-times md:text-gray-500 md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:leading-[18px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:ml-3 md:mt-0.5 md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          textContainerVariant="box-content caret-black min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
          titleVariant="font-bold box-content caret-black leading-[normal] text-start text-clip text-wrap font-times md:font-semibold md:aspect-auto md:box-border md:caret-transparent md:leading-[26px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          descriptionVariant="text-black box-content caret-black leading-[normal] text-start text-clip text-wrap mt-0 font-times md:text-gray-500 md:aspect-auto md:box-border md:caret-transparent md:leading-[18px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:mt-[5px] md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          statsContainerVariant="box-content caret-black gap-x-[normal] block flex-nowrap justify-normal min-h-0 min-w-0 gap-y-[normal] mt-0 md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:flex-wrap md:justify-between md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-[15px] md:scroll-m-0 md:scroll-p-[auto]"
          statItemVariant="box-content caret-black block flex-row min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
          statValueVariant="text-black text-base font-bold box-content caret-black leading-[normal] min-h-0 min-w-0 font-times md:text-gray-400 md:text-sm md:font-semibold md:aspect-auto md:box-border md:caret-transparent md:leading-[22px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          statLabelVariant="text-black text-base box-content caret-black leading-[normal] min-h-0 min-w-0 mt-0 font-times md:text-gray-500 md:text-xs md:aspect-auto md:box-border md:caret-transparent md:leading-[18px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-[3px] md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          creatorContainerVariant="[align-items:normal] box-content caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] mt-0 md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-5 md:scroll-m-0 md:scroll-p-[auto]"
          creatorImageContainerVariant="[align-items:normal] bg-transparent box-content caret-black block h-auto justify-normal min-h-0 min-w-0 w-auto rounded-none md:items-center md:aspect-auto md:bg-neutral-900 md:box-border md:caret-transparent md:flex md:h-[30px] md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[30px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-full"
          creatorImageVariant="box-content caret-black h-auto max-w-none min-h-0 min-w-0 object-fill w-auto md:aspect-auto md:box-border md:caret-transparent md:h-3/6 md:max-w-full md:min-h-[auto] md:min-w-[auto] md:object-contain md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6/12 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
          creatorTextVariant="text-black text-base box-content caret-black basis-auto grow-0 leading-[normal] min-h-0 min-w-0 text-clip text-wrap font-times md:text-gray-500 md:text-xs md:aspect-auto md:box-border md:caret-transparent md:basis-[0%] md:grow md:leading-[18px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-epilogue"
          creatorAddressVariant="text-black box-content caret-black text-wrap md:text-gray-400 md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
        />
      </div>
      <button className="text-gray-600 text-[10px] bg-zinc-900 caret-transparent block leading-[15px] text-center ml-1 p-2 rounded-full">
        <img
          src="https://c.animaapp.com/mh4w5bh5ddZvQu/assets/icon-14.svg"
          alt="Icon"
          className="box-border caret-transparent h-2.5 w-2.5"
        />
      </button>
    </div>
  );
};
